{{- if .Values.istio.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ printf "%s-%s" .Chart.Name .Values.namespace }}
spec:
  {{- with .Values.istio.virtualService.hosts }}
  hosts:
    {{- toYaml . | nindent 4 }}
  {{- end}}
  {{- with .Values.istio.virtualService.gateways }}
  gateways:
    {{- toYaml . | nindent 4 }}
  {{- end}}
  http:
    - route:
        - destination:
            host: {{ printf "%s.%s.svc.cluster.local" .Chart.Name .Values.namespace }}
            port:
              number: {{ .Values.service.port }}
{{- end }}